### ISSUE TITLE
Detecting cancel vs. successful save

### ISSUE THREAD

**Issue by bergr01** [eligrey/FileSaver.js#187] opened 2015-12-01 23:00 UTC
hi,

Can you please advise as to how I'd go about detecting whether after calling saveAs the end-user successfully downloaded the file or proceeded to cancel the download attempt? It wasn't immediately obvious to me after scanning through FileSaver.js content - I see fileSaver.readystate changing to values like fileSaver.DONE in a few locations but these include abort as well. Essentially after end-user downloads the file I want to trigger some subsequent actions - and want to prevent these if user cancels.

**Comment by jimmywarting** [comment] 2016-05-24 12:07
Duplicate of #126

**Closed by jimmywarting** 2016-05-24 12:07 UTC

**Comment by jimmywarting** [comment] 2016-05-24 12:21
The done/abort/writeable event is only genuinely used for the filesystem API in Blink (chrome & opera) but they are not being used so much now since, well we have a[download] link to save blobs for us now. so we don't need to write a blob to a sandboxed filesystem and then copy it to users filesystem.
