### ISSUE TITLE
Update last version in NPM

### ISSUE THREAD

**Issue by themacboy** [eligrey/FileSaver.js#680] opened 2020-11-04 23:27 UTC
Thx in advance

**Comment by themacboy** [comment] 2020-11-17 00:05
hello @jimmywarting ! It is posible to update npm?

**Comment by ehsantoucerkany** [comment] 2020-11-19 12:08
Duplicate of https://github.com/eligrey/FileSaver.js/issues/674

**Comment by jimmywarting** [comment] 2020-11-19 12:18
done

**Closed by jimmywarting** 2020-11-19 12:18 UTC
