### ISSUE TITLE
Create releases here!

### ISSUE THREAD

**Issue by letoss** [eligrey/FileSaver.js#212] opened 2016-03-31 20:03 UTC
Hello guys!

Your library saved my life. It's awesome.

But i don't know why you don't have releases here. The other Github has an old release and I want to be able to download the latest version using npm!

Would be great if you decide to add releases here!

**Comment by oliverlloyd** [comment] 2016-04-18 16:45
An up to date Npm package would indeed be great, possible?

**Comment by DanlanNZ** [comment] 2016-04-27 13:18
duplicate of #200

**Closed** 2016-05-25 20:23 UTC
