### ISSUE TITLE
Force to prompt save as window

### ISSUE THREAD

**Issue by davejack1** [eligrey/FileSaver.js#259] opened 2016-09-02 16:31 UTC
Below is my code for downloading a .dxf file containing a text.

When I try this example, it opens the content of the file to be saved as a new tab.

How can I force it to be saved to disk?

```
var myBtn = document.getElementById('save-btn');

myBtn.addEventListener("click", function()
{
    var blob = new Blob(["HelloWorld"], {type: "text/plain;charset=utf-8"});
    saveAs(blob, "test.dxf");
});
```

**Comment by jimmywarting** [comment] 2016-09-02 16:54
Perhaps not possible... what browser are you using?

**Comment by davejack1** [comment] 2016-09-02 16:56
Safari

**Comment by jimmywarting** [comment] 2016-09-02 17:32
Duplicate of #129 or #12. This is just not possible in Safari. cuz they are taking everything slow

**Closed by jimmywarting** 2016-09-02 17:32 UTC

**Comment by jimmywarting** [comment] 2016-09-02 17:36
It is however possible to save the file to the download folder without showing the prompt dialog but the filename will be "unknown" to me this is much worse then if you can display it in a new tab and let the user use cmd+s to save the file from the browser with a filename then want
