### ISSUE TITLE
Could not download the latest version by bower install

### ISSUE THREAD

**Issue by OukaWang** [eligrey/FileSaver.js#418] opened 2018-03-21 08:02 UTC
My project depends on the file-saver project. But unfortunately, I could not download this project by bower script.

It just download the project folder but could not find the 'fileSaver.js' & 'fileSaver.min.js'.
Does there have something wrong ?

**Comment by boris-petrov** [comment] 2018-03-21 08:18
Duplicate of https://github.com/eligrey/FileSaver.js/issues/409.

**Closed** 2018-09-21 00:12 UTC
