### ISSUE TITLE
Unexpected token export

### ISSUE THREAD

**Issue by jgassie** [eligrey/FileSaver.js#399] opened 2018-01-25 14:57 UTC
I suppose I had been using an older version that was minimized that is no longer on rawgit.com... 
After attempting to use the new version, I now am receiving "Unexpected token export" when this library is being loaded... If you have any immediate insight as to what I should look into for what might be contributing to the error (where the prior version worked well), let me know, thank you!

UPDATE:  So I was using https://cdn.rawgit.com/eligrey/FileSaver.js/24f9aaca/src/FileSaver.js which was yielding the error.... which is what the rawgit site implied I should use... which I switched to the minimized file used in your demo, everything worked again... I'm not certain if that is meant to be a permanent location for the file, but it works for now.

**Comment by eligrey** [comment] 2018-01-25 21:32
If you want to run it on older browsers either build with Babel or include https://cdn.rawgit.com/eligrey/FileSaver.js/5733e40e5af936eb3f48554cf6a8a7075d71d18a/FileSaver.js

I'll publish a tagged release with built JS later today.

**Comment by jgassie** [comment] 2018-01-25 21:40
Sounds good, thank you.  I have only been using this with Chrome so far.

**Comment by mtravis** [comment] 2018-01-27 08:58
I'm also interested in this.

**Comment by MGTHEBOSS** [comment] 2018-02-01 09:33
I confirm the issue. [FileSaver.js](https://raw.githubusercontent.com/eligrey/FileSaver.js/master/src/FileSaver.js) is giving, Uncaught SyntaxError: Unexpected token export error :16. The issue is not present in [minified version](https://cdn.rawgit.com/eligrey/FileSaver.js/e9d941381475b5df8b7d7691013401e171014e89/FileSaver.min.js).

**Comment by Ruffio** [comment] 2018-03-07 11:57
@jgassie , @eligrey has this issue been fixed/resolved and can therefore be closed?

**Comment by jgassie** [comment] 2018-03-07 12:02
yes thank you!

**Comment by Ruffio** [comment] 2018-03-07 12:07
@jgassie then close it ;-)

**Closed** 2018-03-07 12:43 UTC

**Comment by davemerrill** [comment] 2018-07-22 16:41
Downloaded the zip from GitHub as of today, and I do see this error, in Chrome Version 67.0.3396.99 (Official Build) (64-bit). I tried the minified CDN version linked to above, and there's no error, but there's no minified version in the current repo. What's supposed to be happening here?

Also,  using the minified CDN version, neither FileSaver nor saveAs are defined on the page. I'm working on a very simply single page app with no build system or require infrastructure. How is this intended to be used in that case?
