### ISSUE TITLE
the bower component is empty since new releases

### ISSUE THREAD

**Issue by LeonRueda** [eligrey/FileSaver.js#426] opened 2018-03-23 16:16 UTC
When install with bower, the component folder is empty

**Comment by teddy-error** [comment] 2018-03-23 22:49
This occurs in 1.3.6+

```
bower mismatch      Version declared in the json (1.3.3) is different than the resolved one (1.3.6)
```

**Comment by maltem-za** [comment] 2018-03-26 14:49
Duplicate of #409

**Comment by jimmywarting** [comment] 2018-09-21 14:55
closing as dupe

**Closed by jimmywarting** 2018-09-21 14:55 UTC
