### ISSUE TITLE
Downloading multiple files at once

### ISSUE THREAD

**Issue by odflash** [eligrey/FileSaver.js#331] opened 2017-05-09 03:22 UTC
In a sequential call:
saveAs(new Blob(...), "a.txt");
saveAs(new Blob(...), "b.txt");
saveAs(new Blob(...), "c.txt");

I got 3 download  of the same file that was last set.

I think that this is due to the improper scope of the variable save_link defined in
var saveAs = saveAs || (Function (view) {
...
, save_link = doc.createElementNS ("http://www.w3.org/1999/xhtml", "a")
, can_use_save_link = "download" in save_link
...
}

The definition of the save_link object in
, FileSaver = function (blob, name, no_auto_bom) {
...
, save_link = doc.createElementNS ("http://www.w3.org/1999/xhtml", "a")
, can_use_save_link = "download" in save_link
...
}
solves the problem of multiple downloads

Please fix this problem.

**Comment by JimmyBoh** [comment] 2017-11-21 20:21
Is this still an issue? Does this need a PR to implement?

**Comment by stuartpb** [comment] 2018-01-04 05:21
This sounds like a duplicate of #165, fixed in #184.

**Comment by eligrey** [comment] 2018-01-06 12:32
@JimmyBoh @stuartpb Can you repro this? If so, I'll just make a new `<a>` element for each click event.

**Comment by JimmyBoh** [comment] 2018-01-06 15:29
I think my actual issue was regarding the browser blocking any downloads after the initial. Our solution was to just update the security settings for our site to allow multiple downloads. We are pretty close to release so I don't know if we will upgrade to the latest version, but I can try it locally after the weekend.

**Comment by pellejacobs** [comment] 2018-04-19 15:51
I'm having the same issue with Chrome 65. Here is a snippet that reproduces the problem: 

```javascript
import { saveAs } from 'file-saver'
for(const index of [ ...Array(5).keys() ]) {
  console.log(index)
  var blob = new Blob(["Hello world!"], {type: "text/plain;charset=utf-8"});
  saveAs(blob, `hello-world-${index}.txt`);
}
```

This snippet only downloads the last file, `hello-world-4.txt`. 

Here is a repl.it to try it: https://repl.it/@PelleJacobs/SaveAsMultipleFiles

**Comment by DanielRuf** [comment] 2018-04-29 14:15
Does saveAs use promises?

**Comment by jimmywarting** [comment] 2018-04-29 19:06
> Does saveAs use promises?

No. The task is not async. Even doe the writing to the hard drive is async, we have no way of knowing when it has finish writing.

**Comment by tarim** [comment] 2018-07-20 02:32
same issue here... any updates, please?

**Closed** 2018-09-26 10:42 UTC

**Comment by pellejacobs** [comment] 2018-11-05 08:56
@leondroidgeeks We use the following workaround

It's not perfect, but it works for us.

```javascript
download = async () => {
  for(const index of [ ...Array(5).keys() ]) {
    console.log(index)
    var blob = new Blob(["Hello world!"], {type: "text/plain;charset=utf-8"})
    saveAs(blob, `hello-world-${index}.txt`)
    await new Promise(setTimeout) 
  }
}
```

**Comment by alidavid0418** [comment] 2019-05-07 13:20
@pellejacobs it's tricky! thanks
