### ISSUE TITLE
Typed Array and Safari

### ISSUE THREAD

**Issue by photopea** [eligrey/FileSaver.js#221] opened 2016-04-29 08:43 UTC
Hi guys, I am using FileSaver.js for downloading projects in my app Photopea. Many users report, that it does not work in Safari  https://github.com/photopea/photopea/issues/19 . I am using it in the following manner:

    var blob = new Blob([buff]);    // buff is ArrayBuffer with binary data
    saveAs(blob, path);             // path is String

Am I doing anything wrong?

**Comment by jimmywarting** [comment] 2016-05-24 09:08
Seems to look fine to me, safari has support for both typed array and blob constructor, but one thing that Safari isn't good at are saving a blob. Safari don't support a[download] yet

So this seems to be a duplicate of #129

**Closed by jimmywarting** 2016-05-24 09:08 UTC
Labels: Make a Blob, safari
