### ISSUE TITLE
Problems saving in some versions of Safari

### ISSUE THREAD

**Issue by gawry** [eligrey/FileSaver.js#12] opened 2013-01-08 20:32 UTC
Edit by @eligrey: Please tell Apple how this bug is affecting you in https://bugs.webkit.org/show_bug.cgi?id=102914 if you want this fixed. 

Edit by @jimmywarting
The safari bug #102914 has been marked as fixed now

> according to the [commit position](http://trac.webkit.org/changeset/198893), download attribute is fixed in WebKit [v602.1.27](http://trac.webkit.org/browser/trunk/Source/WebCore/Configurations/Version.xcconfig?rev=198893#L24).
> The latest beta build (Safari Technology Preview) is based on WebKit v602.1.25, and of course doesn't contain this patch, so there's no simple way to test.

In the meantime, if you want to support Safari 7, you'll probably want to use [Downloadify](https://github.com/dcneiner/Downloadify) (uses Flash, not HTML5).

---
# Issues we have had with Safari
- [x] **Blob is not supported**<br>
  This has been solved with [Blob.js](https://github.com/eligrey/Blob.js) using [BlobBuilder](https://developer.mozilla.org/en-US/docs/Web/API/BlobBuilder) as fallback and then base64 data uri if that are not supported either
- [x] **URL.createObjectUrl**<br>Has been covered by both FileSaver.js and blob.js
  Blob.js overrule createObjectUrl with it's own base64 url constructor only if it's a "fake blob" (i.e not a File or Blob representation) it will use `window.URL`, fallback to `window.webkitURL` or use it's own base64 function to create those "fake blobs" data-uri
- [ ] **The "can't open blob url"** issue (partly supported) - [screenshot](https://camo.githubusercontent.com/3a2144eb5ff3765c074c0a5510925e2871954d30/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3239393237302f313933383837352f32653363623536632d376635352d313165332d393161632d3965343665643233653735372e706e67)

>             The page you opened redirected you to a page that isn't supported by safari<br>Safari can't open the page <blob-url> becuse Safari can't be redirected to address that begin with "blob:".
- This is mostly cased by unsupported mime type, Safari **do** support opening blob url, but only if it's a mimetype that safari can understand like simple `plain/text` or a common image like `image/png`.
  - This will result in a new tab from which the user can just hit <kbd>⌘</kbd>+<kbd>S</kbd> to save it
- ATM FileSaver.js looks at the mimetype to see if it is `application/octet-stream` (wish is commonly used to force saving files from the server)<br> If it's then it read the blob as base64 using [FileReader](https://developer.mozilla.org/en/docs/Web/API/FileReader) to open a `data:attachment/file" + base64` url in order to save it.
  - It's not possible to create a blob with `attachment/file` type directly and open it, then you will get errors like this: `Failed to load resource: Frame load interrupted` it has to be base64 for some reason...
  - the resulting filename will be "unknown" when doing this
- [ ] **The blank page error** partial supported - (formuly known as "can't open blob url", see above)<br>
  This can easily be reproduced by doing:

``` javascript
window.onclick = function(){
    var blob = new Blob(["Hi"], {type: 'application/octet-stream'});
    var url = URL.createObjectURL(url);
    window.open(url);
}
```

If you replace `window.open` with `location.href =` you will get the `Failed to load resource: Frame load interrupted` and be unable to save the file that is not the case for all mimetype, mimetypes that Safari can display can be opened this way

A little side note here is that window.open only works on trusted events meaning:
- It will only be able to open the url when user interacts with the website like a `onclick` event (more about isTrusted event [here](https://developer.mozilla.org/en/docs/Web/API/Event/isTrusted) - almost pointless becuse browser support)

I have also found out that the trusted event persist for 1000 ms, so you could do:

``` javascript
window.onclick = function(){
    setTimeout(function(){
        var blob = new Blob(["Hi"], {type: 'application/octet-stream'});
        var url = URL.createObjectURL(url);
        window.open(url);
    }, 950); // Any longer then 1sec will make the window.open blocked again
}
```
# So the conclusion here about safari is
1. download attribute in safari is not supported
2. It will try other means to save the blob by opening a new url
3. If the mimetype can be rendered by safari it will be able to display it in a new tab
4. If the mimetype is application/octet-stream:<br>
   4.1 Create a base64 link with FileReader api<br>
   4.2 try to open a new tab using window.open + base64 url<br>
   4.3 if it was more then 1 sec before the user interaction happened it will use the current page instead<br> but that is likely going to fail because (see first example using location.href) `Failed to load resource: Frame load interrupted` This may still work if the mimetype is not `application/octet-stream` and the saveAs was not called synchronous
5. Safari don't have anything like `msSaveAs()`
6. safest way to force the file to be saved is to have a `data:attachment/file" + base64` ready and open that link using window.open() when the user interacts with the website (or at least to it under 1 second)
7. when saving it as a attachment filename will be "unknown"

**Comment by t2n** [comment] 2015-02-06 10:12
Downloading blobs doesn't seem to work on OSX Safari 8.0.2. I can't think of any other way around than to upload locally created file and download it the old way... Or block users from that feature on Safari browser telling them to use Chrome or Firefox to export things. Any thoughts on this?

**Comment by devinivy** [comment] 2015-02-10 20:55
Continues to be a problem.  Just looking for a reasonable workaround.

**Comment by McPants** [comment] 2015-02-13 19:55
:+1:

**Comment by devinivy** [comment] 2015-02-13 20:02
Downloads typically initiate from some user click.  The workaround for safari is to use that click.  Basically, add an event handler to an anchor tag.  If you can synchronously change the href in time during the event handler to a blob URL, then you're all set.  It doesn't exactly cater to every use-case, but it works.

**Comment by halo** [comment] 2015-02-13 20:15
@devinivy Interesting, could you provide a jsfiddle, please?

**Comment by devinivy** [comment] 2015-02-13 21:47
Here!  http://jsfiddle.net/0ts5y7f3/3/
It doesn't work well with `application/octet-stream`, per your jsfiddle above.  But it does allow you to open any attachment in a new window, which I am otherwise completely unable to do with Safari 8.

**Comment by keyscores** [comment] 2015-09-11 16:14
OSX Safari 8.04  the issue persists for .xlsx files using octet-stream.

**Comment by atoftegaard** [comment] 2015-09-21 18:27
Can confirm this issue persists for Safari 8.0.6, using text/plain

**Comment by andreiho** [comment] 2015-09-28 12:06
Issue persists in Safari 8.0.8 (10600.8.9), using "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet".

**Comment by antelle** [comment] 2015-10-03 19:50
So far, an attempt to download a file results in error in Safari 9 as well.
I have found a workaround to download binary files _without opening as plaintext_ in Safari which I have checked Safari 7, 8 and 9.
I have submitted a pull request #175 with workaround for safari.
There's a limitation: you cannot change downloaded file name (it will be 'Unknown'). But it downloads the file with correct content in Safari, without opening it for view.

**Comment by viral2010** [comment] 2015-10-07 12:04
Hi,

I am not able to save file in IE 10. Version # -10.0.9200. When i try to save file from this url - http://eligrey.com/demos/FileSaver.js/, it is giving me same error. I have attached file which i get when i try to save the file and the file is not saved.
![filesave](https://cloud.githubusercontent.com/assets/15014013/10336904/a842f976-6d19-11e5-97fe-df7022697d95.png)

**Comment by Jesse592** [comment] 2015-10-21 09:38
What's the status on this? I still can't get it to work on iOS

**Comment by assadtony** [comment] 2016-03-17 15:39
Any news on this? Still unable to download XLSX files in Safari.
@andreiho @keyscores, did you get to a workaround to download XLSX files? 
Thanks :)

**Comment by jack-fdrv** [comment] 2016-04-05 09:49
With Safari and `var file = new Blob([data], { type: 'application/octet-stream' });` it autosave file but the name is 'Unknown' instead name which I have specified.

**Comment by ciscohsieh** [comment] 2016-04-06 03:14
When I tried using { type: 'application/octet-stream' }, I see "Failed to load resource: Frame load interrupted" in the developer tool console.

**Comment by agairing** [comment] 2016-04-15 13:29
The bug "https://bugs.webkit.org/show_bug.cgi?id=102914" seems now to be fixed. Can anybody assess if the bugfix solves the problem with downloads in Safari - or do we have to wait until the new Safari version is available?

**Comment by antelle** [comment] 2016-04-15 17:51
@agairing according to the [commit position](http://trac.webkit.org/changeset/198893), this is fixed in WebKit [v602.1.27](http://trac.webkit.org/browser/trunk/Source/WebCore/Configurations/Version.xcconfig?rev=198893#L24).
The latest dev build (Safari Technology Preview) is based on WebKit v602.1.25, and of course doesn't contain this path, so there's no simple way to test.
I've just downloaded WebKit Nightly [rev.199584](http://trac.webkit.org/browser/trunk/Source/WebCore/Configurations/Version.xcconfig?rev=199584), [v602.1.29](http://trac.webkit.org/browser/trunk/Source/WebCore/Configurations/Version.xcconfig?rev=199584#L24) and it doesn't work (I tested only the download attribute itself, not FileSaver.js).

**Comment by Rankel** [comment] 2016-04-19 01:01
Woow i see some good progress in this issue with Webkit, i hope to see this fixed soon in stable versions of ios!

**Comment by prafulc** [comment] 2016-06-21 07:11
I am using this package to save an excel file. It is working well with mozilla and chrome but it is not downloading file in safari as Blob is not supported in safari after v6. Here is my code:

`saveAs(new Blob([s2ab(response)],{type:"application/octet-stream"}), fileName)`

**Comment by jimmywarting** [comment] 2016-06-21 07:21
@prafulc what happens instead? Are you doing it async?

**Comment by prafulc** [comment] 2016-06-21 07:51
@jimmywarting yes. Its in my Meteor.call

**Comment by eddieloeffen** [comment] 2016-09-28 00:17
The latest version of Webkit NIghtlies now supports \<a download\>, however there seems to be a bug with FileSaver.js that is stopping the click event being despatched.

https://github.com/eligrey/FileSaver.js/issues/268

**Comment by WuglyakBolgoink** [comment] 2016-10-10 12:16
> If the mimetype can be rendered by safari it will be able to display it in a new tab

we have some problem with latest Safari-Browser version (mobile + desktop). If I click first time ->  image/pdf will be open in same tab, if I click again -> it open a new tab. Sometimes it open new tab from first time... Is it possible to say "open file always in a new tab"?

Mimetypes: "image/png" or "image/jpeg" have same effect...

Thank you for your help!

**Comment by nepaul** [comment] 2016-11-29 09:59
still not work on macOS Sierra Safari Version 10.0.1 (12602.2.14.0.7)!

**Comment by petrunov** [comment] 2016-11-30 12:53
Is there even a solution to this issue? Simply changing the mime type is not working for me.

**Comment by nadelicious** [comment] 2016-12-08 11:30
not working in safari version Version 10.0.1 (11602.2.14.0.7)

**Comment by nadelicious** [comment] 2016-12-08 11:34
not working in safari version Version 10.0.1 (11602.2.14.0.7)

**Comment by francoraconto** [comment] 2017-01-11 18:40
Not working right now on Safari 10. It would be nice to get this information on the presentation page...

**Comment by radek-anuszewski** [comment] 2017-01-24 13:59
I also have this problem. I download file from Angular service:

```
return $http
        .get(baseUrl + '/downloadReport', {
            responseType: 'arraybuffer',
            params: {
                //some params
            },
        })
        .then(DownloadFileService.downloadExcelFile);
```
And then inside `DownloadFileService`:

```
function downloadExcelFile (response) {
    _downloadFile(response.data, _getFileName(response), DOWNLOAD_FILE.OLDER_EXCEL);
}

function _getFileName (response) {
    return response.headers('Filename');
}

function _downloadFile (fileData, fileName, fileType) {
    FileSaver.saveAs(new $window.Blob([fileData], {type: fileType}), fileName);
}
```

But in console I got `blob:http` error. File type is `application/vnd.ms-excel`.

**Comment by Toiny** [comment] 2017-02-06 10:10
Same problem here on Safari 10.0. I can't download an `application/vnd.ms-excel` file type.
But working fine on Chrome & Firefox.

here is a part of my code :

`data.service.ts` :
`exportObject(objectId: string): Observable<any> {
    const args: RequestOptionsArgs = {
      headers: new Headers({ 'Content-Type': 'application/zip' });,
      search: `objectId=${objectId}`,
      responseType: ResponseContentType.Blob
    };
    return this.http.get(`${this.apiUrl}/exportObject`, args)
      .map(data => {
        return data.blob();
      });
  }`

`my-component.ts` :
`this.dataService.exportObject(this.object.id).subscribe(
    blob => {
        saveAs(blob, `${this.object.name}-config.zip`);
    }
)`

**Comment by Toiny** [comment] 2017-02-06 10:16
Same problem here on Safari 10.0. I can't download an `application/vnd.ms-excel` file type.
But working fine on Chrome & Firefox.

here is a part of my code (angular 2) :

data.service.ts :
```
exportObject(): Observable<any> {
  const args: RequestOptionsArgs = {
    headers: new Headers({ 'Content-Type': 'application/zip' });,
    responseType: ResponseContentType.Blob
  };
  
  return this.http.get(${this.apiUrl}/exportObject, args).map(
  data => {
    return data.blob();
  });
}

```
my-component.ts :
```
this.dataService.exportObject().subscribe(
  blob => {
    saveAs(blob,${this.componentObj.name}-config.zip);
  }
);
```

**Comment by sirbarrence** [comment] 2017-02-14 19:46
FileSaver.js works for me in my application and on the demo page in the latest Safari Technology Preview Release 23 (Safari 10.2, WebKit 12604.1.5) on Sierra. Saves to the Downloads folder with the correct filename and everything!

(Might have been fixed in a previous Preview release. I can't recall the last Preview I tried.)

**Comment by sirbarrence** [comment] 2017-02-14 21:43
Also works in Safari 10.1 in the latest macOS Sierra 10.12.4 Beta, so I would guess that real users might get this in the next few months.

**Comment by meletis** [comment] 2017-03-29 08:36
Yes, confirmed. I also works for me in Safari 10.1 released yesterday.

**Comment by davidpelayo** [comment] 2017-05-19 10:25
Confirmed it's working on Safari 10.1, but not in previous versions.

**Comment by jimmywarting** [comment] 2017-05-22 11:02
Should we close this issue now? ;P

**Comment by sirbarrence** [comment] 2017-05-22 12:26
Should probably update the supported browser info in README.md

**Comment by toby5box** [comment] 2017-06-10 18:45
FWIW I can report this problem still exists on 9.1.1 (El Capitan).

**Comment by aishmita-aggarwal** [comment] 2017-06-22 04:08
I am also experiencing the same issue on Safari 9.1.2 (El Capitan).

**Comment by davidpelayo** [comment] 2017-06-22 05:19
Yes. Let's update supported browser in README and close this issue.

**Closed** 2017-06-22 07:01 UTC
Labels: safari

**Comment by Ruffio** [comment] 2017-07-29 08:41
@eligrey if this issue is resolved/closed, should the Frontpage be updated?

Currently it states: 
Safari 6.1+

Blobs may be opened instead of saved sometimes—you may have to direct your Safari users to manually press ⌘+S to save the file after it is opened. Using the application/octet-stream MIME type to force downloads can cause issues in Safari.

**Comment by tayfunyasar** [comment] 2017-10-11 12:27
It still doesn't work in my tablet. 
IOS: 11.0.2 (15A421)

**Comment by CinnamonRage** [comment] 2017-11-09 11:41
I can agree with @tayfunyasar, it's not working on iOS for me. I have submitted a bug report to Apple regarding the lack of download attribute for all the good it's likely to do.

**Comment by ssuess** [comment] 2018-07-06 14:53
Not sure if this helps, but I am able to get ics downloads working in a php library (IcsGenerator), it appears that it is setting some headers on download to make this work:

````
public function download() {
        $_SESSION['calander_invite_downloaded'] = self::DOWNLOADED;
        $generate = $this->_generate();
        header("Pragma: public");
        header("Expires: 0");
        header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
        header("Cache-Control: public");
        header("Content-Description: File Transfer");
        header("Content-type: application/octet-stream");
        header("Content-Disposition: attachment; filename=\"".$this->getFilename()."\"");
        header("Content-Transfer-Encoding: binary");
        header("Content-Length: " . strlen($generate));
        print $generate;
    }
````

Would perhaps setting some of these headers (is that possible in FileSaver.js?) help with the downloading issue in iOS Safari? I would love to be able to do everything in js...

**Comment by dotnetCarpenter** [comment] 2018-11-20 19:34
It's only fixed on Desktop Safari. iOS safari does still not (iOS 12.1) support the download attribute.
https://bugs.webkit.org/show_bug.cgi?id=167341

**Comment by pawepaw** [comment] 2018-12-18 09:43
So what's the recommended workaround for that?

**Comment by generalov** [comment] 2018-12-18 13:57
@pawepaw I suppose that the opening in new tab is expected behavior for Safari <12 on iOS because the browsers do not have an access to file system. This gives the user a chance to save a file with an additional click to the cloud storage.

**Comment by dotnetCarpenter** [comment] 2019-01-09 04:32
I can save a file on iOS but not give it a name. See here: https://dotnetcarpenter.github.io/FileReader_Chrome/

**Comment by crisz** [comment] 2019-04-19 12:03
This is still not working on iOS, with the exact same symptoms as described above. In my opinion this issue should **not** be closed

**Comment by classicPintus** [comment] 2019-05-26 22:04
Confirm for me also. Unfortunately the problem is still there

**Comment by Jason-LI-M** [comment] 2019-06-26 08:49
> I can save a file on iOS but not give it a name. @pawepaw See here: https://dotnetcarpenter.github.io/FileReader_Chrome/

Not working

**Comment by CinnamonRage** [comment] 2019-06-26 11:03
This is resolved in the new safari in iOS 13 with the introduction of three download manager.

**Comment by MrStofkat** [comment] 2019-07-17 14:32
can this be reopened? this is still an existing issue

**Comment by IhorBilobran** [comment] 2019-08-28 08:17
I had the same issue with images download. This helped:
`
const blob = new Blob([file], { type: 'image/jpeg' });
const url = window.URL.createObjectURL(blob);
saveAs(url, fileName);
`

**Comment by DevJhns** [comment] 2020-01-21 15:06
> I had the same issue with images download. iPhone, Safari. This helped:
> `const blob = new Blob([file], { type: 'image/jpeg' });`
> `const url = window.URL.createObjectURL(blob);`
> `saveAs(url, fileName);`

this code allowed you to DOWNLOAD file in your file system or OPEN it in safari tab?

**Comment by HansLanger** [comment] 2020-04-07 17:49
2020 and still the same problem? UNKNOW as name, and can't download octet-stream?? wow.

**Comment by snipe** [comment] 2020-04-07 18:04
@HansLanger Maintaining open source projects takes a lot of time, and sometimes people's priorities change, and life gets in the way. People create software and let you use it for free, so maybe don't be an ass in the face of free labor. Having a crappy attitude doesn't get problems solved any faster.

**Comment by HansLanger** [comment] 2020-04-07 19:06
@snipe: If you understand the problem you would understand that I was NOT complaining about FileSaver.js. I was complaining about Safari (which is not free). Sorry for the confusion.

**Comment by snipe** [comment] 2020-04-07 19:38
@HansLanger thanks for the clarification. (Safari is free, if you don't mind dropping $1k on an iPhone ;-) )

Did you try the solution @DevJhns mentioned?

**Comment by HansLanger** [comment] 2020-04-07 20:01
> @HansLanger thanks for the clarification. (Safari is free, if you don't mind dropping $1k on an iPhone ;-) )
> 
> Did you try the solution @DevJhns mentioned?

Yes, I tried everything on an Iphone. It just does not work. The Initial @gawry post describes everything perfectly, its a great information, but Apple has not solve the problem, and that is why my first comment.

**Comment by JamesDougherty** [comment] 2020-06-08 13:24
Looks like the "download" attribute was added in iOS 13 as of April 2020.

> Support for the "download" attribute was added in iOS 13.0.
>
> If you have a specific use case with the "download" attribute that doesn't work in iOS 13.0 or later, you need to file a new bug here on bugs.webkit.org with steps to reproduce and (if possible) a > reduced test case that will reproduce the issue.

[https://bugs.webkit.org/show_bug.cgi?id=167341](https://bugs.webkit.org/show_bug.cgi?id=167341)

**Comment by seanlee10** [comment] 2024-03-02 08:21
> > I had the same issue with images download. iPhone, Safari. This helped:
> > `const blob = new Blob([file], { type: 'image/jpeg' });`
> > `const url = window.URL.createObjectURL(blob);`
> > `saveAs(url, fileName);`
> 
> this code allowed you to DOWNLOAD file in your file system or OPEN it in safari tab?

I tried it and the file was opened in current tab. it didn't download.

**Comment by Bonfims** [comment] 2024-07-25 13:28
> window.URL.createObjectUR

same here, i want to open or download the blob on a new tab. :(
