### ISSUE TITLE
File save issue in Safari

### ISSUE THREAD

**Issue by bhattkrishna19** [eligrey/FileSaver.js#129] opened 2015-02-12 12:46 UTC
I am using this code 

``` javascript
var blob = new Blob([atob(response.payload)], {
    "data":"attachment/csv;charset=utf-8;"
});
saveAs(blob, fname);
```

Here response.payload is blob data. Its working fine in all browsers but in safari file getting downloaded without name and opening a blank page also.  Any help will be highly appreciated.

**Comment by DanielMSchmidt** [comment] 2015-03-02 10:06
This seems to be a missing feature: https://github.com/eligrey/FileSaver.js#supported-browsers

**Comment by ragefuljoe** [comment] 2015-03-31 16:03
what is the current recommended way to save things in safari 8? downloadify doesn't seem to work for me, or at least have not found a demo that works in safari.  using saveas just silent fails in my test while working in other browsers.

**Comment by MichelFloyd** [comment] 2015-05-19 16:54
I'm seeing the same problem. Certain file types (e.g. images) open in a new browser tab as blob:... Other file types (e.g. MS Office documents) open a new blank browser tab with no URL at all in the address bar and no file is downloaded. Safari 7.1.5

**Comment by cvrebert** [comment] 2015-05-26 19:06
Duplicate of #12?

**Comment by MichelFloyd** [comment] 2015-05-26 19:10
Seems to be == #12

**Comment by zerdos** [comment] 2016-04-12 12:25
So the problem is the time. If the saveAs happens more than 1 second after the click what triggered it, the plugin will overwrite the current window.

**Comment by ivanstojkovicapps** [comment] 2016-04-15 12:20
having the same problem in Safari. Firefox and Chrom are working! How to prevent this?

**Comment by mroftalp** [comment] 2016-04-22 10:50
If there's no fix yet, how would I make the saveAs open a new tab instead of overwriting the current window?

**Comment by asith-w** [comment] 2016-04-27 06:08
is there any update on this issue ?

**Comment by orenmagen100** [comment] 2016-05-10 14:24
plz?

**Comment by cshanejennings** [comment] 2016-05-19 15:40
Any movement on this?

**Comment by cvrebert** [comment] 2016-05-19 17:06
They still have some work to do; see the transitive dependencies of that bug. Lots of recent-ish activity that looks promising though.

**Comment by jimmywarting** [comment] 2016-05-31 15:13
Try setting the mimetype to `application/octet-stream` to force saving. You will not be able to set the filename, it will default to "unknown" but it's the best you got, another option is to set the mimetype to "text/plain" so it will open it in a new tab so the client can decide where to save and also name it.

```javascript
var blob = new Blob(['"User","Text"'], {
    "type":"application/octet-stream"
})
saveAs(blob);
```

**Comment by meash-nrel** [comment] 2017-01-25 20:18
Looks like Safari 10.1 finally supports the Download attrib.

http://caniuse.com/#feat=download
https://webkit.org/status/#feature-download-attribute

**Closed** 2018-09-21 10:36 UTC
Labels: safari
